#!/bin/sh /etc/rc.common
# Copyright (C) 2016 Aleksander Morgado <aleksander@aleksander.es>
# Ash shell 修复版

USE_PROCD=1
START=99
STOP=10

NAME="modemserver"
DAEMON="/usr/bin/$NAME"
PID_FILE="/var/run/$NAME.pid"
PORT=8080

start_service() {
    sleep 1
    procd_open_instance
    procd_set_param command "$DAEMON" -port "$PORT"
    procd_set_param pidfile "$PID_FILE"
    procd_set_param respawn 30 5
    procd_close_instance
}

stop_service() {
    rm -f "$PID_FILE"
}

restart() {
    stop; start
}
