#!/bin/sh /etc/rc.common
START=99
STOP=10
USE_PROCD=1

NAME="quectel-CM-M"
DAEMON="/usr/bin/$NAME"

start_service() {
    sleep 3
    procd_open_instance
    procd_set_param command "$DAEMON" -i usb0 -4 -6 -s cmnet
    procd_set_param respawn 30 5 0
    procd_close_instance
}

stop_service() {
    killall quectel-CM-M 2>/dev/null
}

restart() {
    stop; start
}
